apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: simplewebsites.mbx360.de
spec:
  group: mbx360.de
  names:
    kind: SimpleWebsite
    listKind: SimpleWebsiteList
    plural: simplewebsites
    singular: simplewebsite
  scope: Namespaced  # or Cluster if it's a cluster-scoped resource
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                domain:
                  type: string
                siteName:
                  type: string
                files:
                  type: array
                  items:
                    type: object
                    properties:
                      filename:
                        type: string
                      content:
                        type: string