apiVersion: v1
kind: ServiceAccount
metadata:
  name: simplewebsite-sa
  namespace: simplewebsite
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: simplewebsite
  name: simplewebsite-operator-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "deployments", "configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["mbx360.de"]
    resources: ["simplewebsites"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: simplewebsite-operator-rolebinding
  namespace: simplewebsite
subjects:
  - kind: ServiceAccount
    name: simplewebsite-sa
    namespace: simplewebsite
roleRef:
  kind: Role
  name: simplewebsite-operator-role
  apiGroup: rbac.authorization.k8s.io
