# kubernetes.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplewebsite-operator
  namespace: simplewebsite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simplewebsite-operator
  template:
    metadata:
      labels:
        app: simplewebsite-operator
    spec:
      serviceAccountName: simplewebsite-sa
      containers:
        - name: simplewebsite-operator
          imagePullPolicy: Always
          image: mibexx/k8s-operator-simplewebsite:1.0.0
          command: ["python", "main.py"]